# Generated by Django 5.2.2 on 2025-06-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_views_counter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="views_counter",
        ),
    ]
